[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
POMDPGifs = "7f35509c-0cb9-11e9-0708-2928828cdbb7"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
QuickPOMDPs = "8af83fb2-a731-493c-9049-9e19dbce6165"
