#name = "VDPTag"
#uuid = "eee7fc60-28e4-11ea-394c-f98382548851"
#authors = ["Chandler Kilpatrick <crskilpatrick807@gmail.com>"]
#version = "0.1.0"

[deps]
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
VDPTag2 = "1859f924-e7ac-11e9-25da-97193e6325a8"
